/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as DeferRouteImport } from './routes/defer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'

const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferRoute = DeferRouteImport.update({
  id: '/defer',
  path: '/defer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/defer': typeof DeferRoute
  '/stream': typeof StreamRoute
  '/api/graphql': typeof ApiGraphqlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/defer': typeof DeferRoute
  '/stream': typeof StreamRoute
  '/api/graphql': typeof ApiGraphqlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/defer': typeof DeferRoute
  '/stream': typeof StreamRoute
  '/api/graphql': typeof ApiGraphqlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/defer' | '/stream' | '/api/graphql'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/defer' | '/stream' | '/api/graphql'
  id: '__root__' | '/' | '/defer' | '/stream' | '/api/graphql'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeferRoute: typeof DeferRoute
  StreamRoute: typeof StreamRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defer': {
      id: '/defer'
      path: '/defer'
      fullPath: '/defer'
      preLoaderRoute: typeof DeferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeferRoute: DeferRoute,
  StreamRoute: StreamRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
